name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore eng:${{ steps.extract_branch.outputs.branch }}
    - name: Build
      run: dotnet build --configuration Release --no-restore eng:${{ steps.extract_branch.outputs.branch }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal eng:${{ steps.extract_branch.outputs.branch }}
