name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ${GITHUB_REF##*/}
    - name: Build
      run: dotnet build --configuration Release --no-restore ${GITHUB_REF##*/}
    - name: Test
      run: dotnet test --no-restore --verbosity normal ${GITHUB_REF##*/}
